In [0]:
import numpy as numpy
import scipy as scipy
from sklearn import cluster
import matplotlib.pyplot as plt

In [0]:
PointClusterNumber=numpy.zeros(400)
print(PointClusterNumber)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [0]:
Visited=numpy.zeros(400,'int')
print(Visited)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [0]:
'''
akses elemen dengan indeks
mengiterasi isi list
menghitung panjang list dengan len()
menghitung kemunculan nilai tertentu dengan count()
menambah nilai baru dengan append()
mencari posisi suatu nilai dengan index()
menyisipkan suatu nilai ke posisi tertentu dengan insert()
membuang nilai tertentu dengan pop()
membuang nilai tertentu dengan remove()
menyambung list dengan extend()
membalik urutan list dengan reverse()
membalik urutan list dengan sort()
mencari nilai max dengan max()
mencari nilai min dengan min()
mencari nilai sum dengan sum()
'''

'\nakses elemen dengan indeks\nmengiterasi isi list\nmenghitung panjang list dengan len()\nmenghitung kemunculan nilai tertentu dengan count()\nmenambah nilai baru dengan append()\nmencari posisi suatu nilai dengan index()\nmenyisipkan suatu nilai ke posisi tertentu dengan insert()\nmembuang nilai tertentu dengan pop()\nmembuang nilai tertentu dengan remove()\nmenyambung list dengan extend()\nmembalik urutan list dengan reverse()\nmembalik urutan list dengan sort()\nmencari nilai max dengan max()\nmencari nilai min dengan min()\nmencari nilai sum dengan sum()\n'

In [0]:
def set2List(NumpyArray):
    list = []
    for item in NumpyArray:
        list.append(item.tolist())
    return list

In [0]:
cluster=[1,2,3,4]
for k in range (len(cluster)):
    print("hai")
    cluster.pop()
print(cluster)

hai
hai
hai
hai
[]


In [0]:
a = [6,7]
for i in a:
    print(i)

6
7


In [0]:
PointNeighbors=[1,5,3,4]
PointNeighbors2=[]

In [0]:
PointNeighbors.index(2)

ValueError: 2 is not in list

In [0]:
PointNeighbors=numpy.where(2<3)[0]
#PointNeighbors=set2List(PointNeighbors2) 

In [0]:
print(PointNeighbors2)

[]


In [0]:
print("hai - %a" % (PointNeighbors))

hai - [(1, 2, 3, 5), (1, 2, 1, 6)]


In [0]:
output = [(1,2,3,5), (1,2,1,6)]

#print (output[1, 2])  # your error
#print (output[(1, 2)]) # your error as well - these are equivalent calls

print (output[0][3]) # ok
print (numpy.array(output)[1, 2] ) # ok
print (numpy.array(output)[(1, 2)]) # ok
print (numpy.array(output)[1][2]) # ok
print(output)

5
1
1
1
[(1, 2, 3, 5), (1, 2, 1, 6)]


In [0]:
def GenerateData():
    x1=numpy.random.randn(5,2)
#     x2x=numpy.random.randn(80,1)+12
#     x2y=numpy.random.randn(80,1)
#     x2=numpy.column_stack((x2x,x2y))
    x2=numpy.random.randn(5,2)+12
    x3=numpy.random.randn(2,2)+8
    x4=numpy.random.randn(5,2)+15
    z=numpy.concatenate((x1,x2,x3,x4))
    return z

In [6]:
Data=GenerateData()
print(Data)
print(Data.shape)

[[-0.66443855 -1.20211367]
 [-0.47593447 -0.58121403]
 [ 1.15738956 -1.16371774]
 [ 0.81609435 -0.84274812]
 [-0.81073292  0.63973846]
 [10.83566817 13.60515227]
 [11.29132431 11.12071576]
 [11.72398428  8.83141547]
 [12.72089691 13.89963785]
 [10.21532674 11.81625959]
 [ 8.51262229  7.51338719]
 [ 8.26609499  8.70816166]
 [14.59095714 13.43008123]
 [14.90073686 15.36788927]
 [15.69937279 13.47838289]
 [16.34442956 14.30072841]
 [15.31751899 15.91649903]]
(17, 2)


In [0]:
get_data=[1,3,4,5,7,2]

In [7]:
Data_bck=Data.copy()
print(Data_bck)
print(Data_bck.shape)

[[-0.66443855 -1.20211367]
 [-0.47593447 -0.58121403]
 [ 1.15738956 -1.16371774]
 [ 0.81609435 -0.84274812]
 [-0.81073292  0.63973846]
 [10.83566817 13.60515227]
 [11.29132431 11.12071576]
 [11.72398428  8.83141547]
 [12.72089691 13.89963785]
 [10.21532674 11.81625959]
 [ 8.51262229  7.51338719]
 [ 8.26609499  8.70816166]
 [14.59095714 13.43008123]
 [14.90073686 15.36788927]
 [15.69937279 13.47838289]
 [16.34442956 14.30072841]
 [15.31751899 15.91649903]]
(17, 2)


In [17]:
#https://stackoverflow.com/questions/10996140/how-to-remove-specific-elements-in-a-numpy-array
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html
#Cara menghapus data numpy array spesifik pada indek ke -
print(type(Data))
Cek = numpy.delete(Data,get_data,0)
print(Cek)
for k in get_data:
    print(k)
    # print(Data[k])
    # Data=numpy.delete(Data,k,0)
    # print("cek")

<class 'numpy.ndarray'>
[[-0.66443855 -1.20211367]
 [11.29132431 11.12071576]
 [12.72089691 13.89963785]
 [10.21532674 11.81625959]
 [ 8.51262229  7.51338719]
 [ 8.26609499  8.70816166]
 [14.59095714 13.43008123]
 [14.90073686 15.36788927]
 [15.69937279 13.47838289]
 [16.34442956 14.30072841]
 [15.31751899 15.91649903]]
1
3
4
5
7
2


In [0]:
print(Data)
print(Data.shape)

[[ 0.62390038 -1.49018197]
 [ 1.33229236 -1.56437743]
 [-1.31496692  1.70338577]
 [ 9.54314436 12.10999758]
 [11.88259767 11.05229223]
 [11.67836256 10.92327977]
 [12.56497534 11.31574658]
 [ 8.61499668  9.92512636]
 [ 7.83025095  7.69302994]
 [16.56465826 15.00560701]
 [15.49089055 13.48656614]
 [14.44635851 15.19412241]
 [15.57782576 14.46954243]
 [15.10706214 14.54658959]]
(14, 2)


In [0]:
foo = [2,4,5,6,7]
bar = [4, 5, 6,2,3,4]

In [0]:
for f, b in zip(foo, bar):
    print(f, b)

In [0]:
foo = numpy.unique(foo, bar)
bar = [100]
print(foo)
foo = numpy.unique(foo, bar)
print(foo)

(array([106, 107, 108, 109, 110, 111]), array([0, 1, 2, 3, 4, 5]))
(array([  0,   1,   2,   3,   4,   5, 106, 107, 108, 109, 110, 111]), array([ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5]))


In [0]:
a=numpy.array([2,3,4,5])
b=numpy.array([1,2,4])
b=numpy.unique(numpy.unique(numpy.concatenate((a,b),0)))
print(b)

[1 2 3 4 5]
